apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{ .Release.Name }}-generate-enterprise-ingress"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100g"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: {{ .Values.generateenterprise.host }}
    http:
      paths:
      - path: /generate(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: "{{ .Release.Name }}-generate-enterprise-service"
            port:
              number: {{ .Values.generateenterprise.port }}